
namespace: ""
imagepullsecrets: devregistrysecrett
dockerhub: ghcr.io/sunbird-aiassistant

replicaCount: 1
repository: "adminutil"
image_tag: "1.0.0"
network:
  port: 4000
  targetport: 4000
strategy:
  type: RollingUpdate
  maxsurge: 25%
  maxunavailable: 25%

healthcheck: true
readinessProbe:
    httpGet:
      path: /health
      port: 4000
    initialDelaySeconds: 15
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 2
livenessProbe:
  httpGet:
    path: /health
    port: 4000
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 2
adminutilenv:
  JAVA_OPTS: "-Xms256m -Xmx256m"
  SERVER_PORT: '"4000"'
  AM_ADMIN_API_ENDPOINT: "http://kong:8001"
  SPRING_PROFILES_ACTIVE: production
  DEFAULT_CONSUMER_GROUP: contentUser
  ENDPOINTS_HEALTH_ID: apihealth
  ENDPOINTS_HEALTH_SENSITIVE: '"false"'
  ENDPOINTS_METRICS_ID: metrics
  ENDPOINTS_METRICS_SENSITIVE: '"false"'
  AM_ADMIN_API_KEYS: "mobile_device,desktop_device,portal_anonymous,portal_loggedin,access"
  AM_ADMIN_API_MOBILE_DEVICE_BASEPATH: "/keys/"
  AM_ADMIN_API_MOBILE_DEVICE_KEYPREFIX: '"mobile_devicev2_key"'
  AM_ADMIN_API_MOBILE_DEVICE_KEYSTART: '"1"'
  AM_ADMIN_API_MOBILE_DEVICE_KEYCOUNT: '"10"'
  AM_ADMIN_API_DESKTOP_DEVICE_BASEPATH: "/keys/"
  AM_ADMIN_API_DESKTOP_DEVICE_KEYPREFIX: '"desktop_devicev2_key"'
  AM_ADMIN_API_DESKTOP_DEVICE_KEYSTART: '"1"'
  AM_ADMIN_API_DESKTOP_DEVICE_KEYCOUNT: '"10"'
  AM_ADMIN_API_PORTAL_ANONYMOUS_BASEPATH: "/keys/"
  AM_ADMIN_API_PORTAL_ANONYMOUS_KEYPREFIX: '"portal_anonymous_key"'
  AM_ADMIN_API_PORTAL_ANONYMOUS_KEYSTART: '"1"'
  AM_ADMIN_API_PORTAL_ANONYMOUS_KEYCOUNT: '"10"'
  AM_ADMIN_API_PORTAL_LOGGEDIN_BASEPATH: "/keys/"
  AM_ADMIN_API_PORTAL_LOGGEDIN_KEYPREFIX: '"portal_loggedin_key"'
  AM_ADMIN_API_PORTAL_LOGGEDIN_KEYSTART: '"1"'
  AM_ADMIN_API_PORTAL_LOGGEDIN_KEYCOUNT: '"10"'
  AM_ADMIN_API_ACCESS_BASEPATH: "/keys/"
  AM_ADMIN_API_ACCESS_KEYPREFIX: '"accessv1_key"'
  AM_ADMIN_API_ACCESS_KEYSTART: '"1"'
  AM_ADMIN_API_ACCESS_KEYCOUNT: '"10"'
  ACCESS_TOKEN_VALIDITY: '"43200"'
  LEARNER_BASE_API_URL: '"http://kong:8000"'
  EMBED_ROLE: '"true"'
  LEARNER_API_AUTH_KEY: '""'
adminutilConfig:
  replicaCount: 1
  autoscaleEnabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1024Mi
