### Default variable file for storysakhi-service ###
environment: "dev"
telemetry_url: "http://telemetry-service:9001"
telemetry_log_enabled: "true"

namespace: ""
imagepullsecrets: ""
dockerhub: ""

ss_repository: "story-api-service"
ss_image_tag: "1.0.0"
ss_log_level: "INFO"
ss_docs_min_score: "0.2"
ss_open_api_key: ""
ss_bhasini_endpoint_url: ""
ss_bhasini_api_key: ""
ss_marqo_url: ""
ss_oci_endpoint_url: ""
ss_oci_region_name: ""
ss_oci_bucket_name: ""
ss_oci_access_key: ""
ss_oci_secret_key: ""
ss_openai_baseurl: ""
ss_openai_version: ""
ss_gpt_model: ""

network:
  port: 8000
  targetport: 8000
strategy:
  type: RollingUpdate
  maxsurge: 25
  maxunavailable: 25

#{{ storysakhi_liveness_readiness | to_nice_yaml }}

storysakhiConfig:
  replicaCount: 1
  autoscaleEnabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: ""
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1024Mi