### Default variable file for activitysakhi-service ###
environment: "dev"
telemetry_url: "http://telemetry-service:9001"
telemetry_log_enabled: "true"

namespace: ""
imagepullsecrets: ""
dockerhub: ""

as_repository: "activity_sakhi_api_service"
as_image_tag: "r2.0.0"
as_log_level: INFO
as_openai_baseurl: ""
as_openai_version: ""
as_gpt_model: ""
as_config_ini_path: "config.ini"
as_top_docs_to_fetch: "5"
as_redis_port: 6379
as_redis_db: 1

network:
  port: 8000
  targetport: 8000
network_wrapper:
  port: 7000
  targetport: 7000
strategy:
  type: RollingUpdate
  maxsurge: 25
  maxunavailable: 25

#{{ activitysakhi_liveness_readiness | to_nice_yaml }}

activityConfig:
  replicaCount: 1
  autoscaleEnabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1024Mi
